version: '3.4'

services:
  responder-test:
    image: responder-test
    build: ./app
    command: uvicorn --host 0.0.0.0 --port 8080 --log-level debug --reload main:api
    volumes:
      - ./app:/app/
    ports:
      - '8089:8080'
